apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2  # Podien määrä
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: carmarketplaceaksregistry.azurecr.io/car-marketplace-backend:latest  # ACR:n Docker-kuva
        ports:
        - containerPort: 4000  # Portti, jota sovellus kuuntelee
        env:  # Ympäristömuuttujat
        - name: NODE_ENV
          value: "production"
        resources:  # Resurssirajoitukset (valinnainen)
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
